// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2BVyapKVAcTCobWfOeQFQOi7UZ1wS_Q',
    appId: '1:1042438246335:web:7edbb104be104a52a85b0a',
    messagingSenderId: '1042438246335',
    projectId: 'cartify-8e04d',
    authDomain: 'cartify-8e04d.firebaseapp.com',
    storageBucket: 'cartify-8e04d.firebasestorage.app',
    measurementId: 'G-JHW5TDT2N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEq4oYtnOZ3RmD4L-g7BC7Y4LNLp61qhU',
    appId: '1:1042438246335:android:d8c0273d7315f414a85b0a',
    messagingSenderId: '1042438246335',
    projectId: 'cartify-8e04d',
    storageBucket: 'cartify-8e04d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYOOj6qFLX4oYETKev_Vs6o9133bxsO6o',
    appId: '1:1042438246335:ios:0ddf8c5726a6b53aa85b0a',
    messagingSenderId: '1042438246335',
    projectId: 'cartify-8e04d',
    storageBucket: 'cartify-8e04d.firebasestorage.app',
    iosBundleId: 'com.example.cartify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYOOj6qFLX4oYETKev_Vs6o9133bxsO6o',
    appId: '1:1042438246335:ios:0ddf8c5726a6b53aa85b0a',
    messagingSenderId: '1042438246335',
    projectId: 'cartify-8e04d',
    storageBucket: 'cartify-8e04d.firebasestorage.app',
    iosBundleId: 'com.example.cartify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ2BVyapKVAcTCobWfOeQFQOi7UZ1wS_Q',
    appId: '1:1042438246335:web:7f18a59af78064d9a85b0a',
    messagingSenderId: '1042438246335',
    projectId: 'cartify-8e04d',
    authDomain: 'cartify-8e04d.firebaseapp.com',
    storageBucket: 'cartify-8e04d.firebasestorage.app',
    measurementId: 'G-GCP0H15RZF',
  );
}
